#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jul 04 20:51:05 CEST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim lcd_controller_tb_func_synth -key {Post-Synthesis:sim_1:Functional:lcd_controller_tb} -tclbatch lcd_controller_tb.tcl -log simulate.log"
xsim lcd_controller_tb_func_synth -key {Post-Synthesis:sim_1:Functional:lcd_controller_tb} -tclbatch lcd_controller_tb.tcl -log simulate.log

