webtalk_init -webtalk_dir /nas/ei/home/ge93zow/lab/skeleton/projlab/projlab.sim/sim_1/synth/func/xsim/xsim.dir/lcd_controller_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul  4 20:51:05 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174114165_1777585303_210790245_429" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "234c885a-4df9-477e-81ec-26d2a656652d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "31bef746fe0249eea5f7bea39abcd7a5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4652.005 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "24" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "1069 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "18 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "238" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "166" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.36_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "429560_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1357161007 -regid "174114165_1777585303_210790245_429" -xml /nas/ei/home/ge93zow/lab/skeleton/projlab/projlab.sim/sim_1/synth/func/xsim/xsim.dir/lcd_controller_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html /nas/ei/home/ge93zow/lab/skeleton/projlab/projlab.sim/sim_1/synth/func/xsim/xsim.dir/lcd_controller_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm /nas/ei/home/ge93zow/lab/skeleton/projlab/projlab.sim/sim_1/synth/func/xsim/xsim.dir/lcd_controller_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
