webtalk_init -webtalk_dir /nas/ei/home/ge93zow/lab/skeleton/projlab/projlab.sim/sim_1/behav/xsim/xsim.dir/lcd_controller_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul  5 14:24:05 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174114165_1777585303_210790245_429" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "234c885a-4df9-477e-81ec-26d2a656652d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "31bef746fe0249eea5f7bea39abcd7a5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "41" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4697.849 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "15001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "123320_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4192515077 -regid "174114165_1777585303_210790245_429" -xml /nas/ei/home/ge93zow/lab/skeleton/projlab/projlab.sim/sim_1/behav/xsim/xsim.dir/lcd_controller_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /nas/ei/home/ge93zow/lab/skeleton/projlab/projlab.sim/sim_1/behav/xsim/xsim.dir/lcd_controller_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /nas/ei/home/ge93zow/lab/skeleton/projlab/projlab.sim/sim_1/behav/xsim/xsim.dir/lcd_controller_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
