#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Jul 04 20:43:51 CEST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 31bef746fe0249eea5f7bea39abcd7a5 --incr --debug typical --relax --mt 8 --maxdelay -L xil_defaultlib -L MFclock -L simprims_ver -L secureip --snapshot lcd_controller_tb_time_synth -transport_int_delays -pulse_r 0 -pulse_int_r 0 -pulse_e 0 -pulse_int_e 0 xil_defaultlib.lcd_controller_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 31bef746fe0249eea5f7bea39abcd7a5 --incr --debug typical --relax --mt 8 --maxdelay -L xil_defaultlib -L MFclock -L simprims_ver -L secureip --snapshot lcd_controller_tb_time_synth -transport_int_delays -pulse_r 0 -pulse_int_r 0 -pulse_e 0 -pulse_int_e 0 xil_defaultlib.lcd_controller_tb xil_defaultlib.glbl -log elaborate.log

